#!/usr/bin/env bash

gem install rubygems-mirror --no-document
cd $GOPATH/src/github.com/akr/gem-codesearch
export RUBYGEMS_MIRROR_ONLY_LATEST=true
ulimit -n 8192
rake mirror unpack
gem uninstall rubygems-mirror --force
rm $CSEARCHINDEX
cindex latest-gem
