#!/usr/bin/env ruby

require "find"
require "open3"
require "pathname"

require "parallel"

RB_EXT_NAMES = %w[.rb .ru .gemspec .rake .cmd .gemfile .thor]
C_EXT_NAMES = %w[.c .h .cpp .hpp]

Parallel.map(Dir.glob("latest-gem/*").shuffle, in_processes: 1) do |dir|
  Find.find(dir) { |fn|
    st = File.lstat(fn)
    if st.file?
      if C_EXT_NAMES.any? { |ext| fn.end_with?(ext) }
        next
      elsif !(RB_EXT_NAMES.any? { |ext| fn.end_with?(ext) } || Pathname(fn).extname.empty?)
        File.unlink fn
        puts "removed: #{fn}"
        next
      else
        _, _, _, wait_thr = *Open3.popen3("ruby -c #{fn}")
        if wait_thr.value.exitstatus != 0
          File.unlink fn
          puts "removed: #{fn}"
        end
      end
    end
  }
end
