source :rubygems

gem 'rails'
gem 'mysql2'
gem 'sorcery'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'haml-rails'
gem 'pry-rails'

group :test do
  gem 'rspec-rails', group: :development
  gem 'capybara'
  gem 'launchy'
  gem 'factory_girl_rails'
end
