# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"

  config.vm.synced_folder "../../../../github.com", "/vagrant/github.com"

  config.vm.provision :itamae do |config|
    config.recipes = ['../recipe_apt.rb']
    config.json = '../node.json'
  end
end
