#!/usr/bin/env ruby
require 'parallel'

devs = %w(2.4.0-dev)

Parallel.map(devs) do |dev|
  system "rbenv install #{dev} --force"
end

Parallel.map(devs do |dev|
  gem_cmd = File.expand_path("~/.anyenv/envs/rbenv/versions/#{dev}/bin/gem")
  system "yes | #{gem_cmd} update"
  system "yes | #{gem_cmd} cleanup"
end
