[general]
live_config_reload = true
import = [
    "~/Documents/github.com/alacritty/alacritty-theme/themes/github_dark_default.toml"
]

[window]
blur = true
opacity = 0.8
padding ={ x = 4, y = 2 }
dimensions = { columns = 180, lines = 80 }

[scrolling]
history = 100000
multiplier = 5

[font]
size = 14.0
offset = { x = 0, y = 2 }
normal = { family = "HackGen Console NF", style = "Regular" }
bold = { family = "HackGen Console NF", style = "Bold" }
italic = { family = "HackGen Console NF", style = "Italic" }
bold_italic = { family = "HackGen Console NF", style = "Bold Italic" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux -u"] }
