cask_args appdir: "/Applications"

brew "tmux"
brew "fish"
brew "fzf"
brew "git"
brew "git-lfs"
brew "git-open"
brew "git-extras"
brew "git-secrets"
brew "gnupg"
brew "pinentry-mac"
brew "hub"
brew "diff-so-fancy"
brew "ghq"
brew "lsd"
brew "bat"
brew "ripgrep"
brew "fd"
brew "fx"
brew "zoxide"
brew "tealdeer"
brew "direnv"
brew "hexyl"
brew "procs"
brew "sd"
brew "dog"

brew "automake"
brew "autoconf"
brew "openssl"
brew "gdbm"
brew "readline"
brew "gmp"
brew "coreutils"
brew "findutils"
brew "libtool"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "gzip"
brew "gawk"
brew "bison"
brew "rsync"
brew "wget"
brew "ffmpeg"
brew "consul-template"

cask "docker"
brew "go"
brew "node"
brew "deno"
brew "cmake"
brew "ninja"
brew "maven"
tap "homebrew/cask-versions"
cask "adoptopenjdk8"
brew "bazel"
brew "clang-format"
brew "aspell"
brew "circleci"
brew "m-cli"
brew "s3cmd"
brew "xdelta"
brew "terraform"
brew "unrar"
brew "llvm"
brew "postgresql"
brew "mysql"
brew "pkg-config"
brew "imagemagick"
brew "imagemagick@6"
brew "vips"
brew "re2"
brew "yajl"
brew "gpgme"
brew "libidn"
brew "icu4c"
brew "protobuf"
brew "ragel"
brew "parallel"
brew "kubernetes-helm"
brew "krew"
brew "php"
brew "composer"
brew "guetzli"
brew "lcov"
brew "ansible"
brew "mackup"
brew "mas"
brew "sshuttle"

tap "homebrew/cask"
cask "google-cloud-sdk"

tap "github/gh"
brew "gh"

brew "snapcraft"
cask "multipass"
cask "alacritty"

tap "heroku/brew"
brew "heroku"

brew "python@3.9"
brew "pipenv"
brew "openstackclient"
brew "awscli"
tap "aws/tap"
brew "aws-sam-cli"

tap "fujiwara/tap"
brew "aswrap"

tap "buildpacks/tap"
brew "pack"

tap "shopify/shopify"
brew "toxiproxy"

tap "nektos/tap"
brew "act"

tap "homebrew/cask-fonts"
cask "font-ricty-diminished"
cask "font-hack-nerd-font"
cask "font-source-han-code-jp"

mas "Xcode", id: 497799835
mas "Apple Developer", id: 640199958
mas "Pages", id: 409201541
mas "Numbers", id: 409203825
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Pixelmator", id: 407963104
mas "1Password 7", id: 1333542190
mas "Display Menu", id: 549083868
