#!/usr/bin/env ruby
require 'open3'
require 'parallel'

Parallel.map(Dir.glob('*/*/*').shuffle) do |dir|
  next unless File.directory? dir
  cleanup = false

  Dir.chdir(dir) do
    next unless File.directory?('.git')
    puts dir
    branch = dir.include?('rubysl') ? '2.0' : 'master'
    `git checkout #{branch}`
    _, _, stderr = *Open3.popen3('git remote prune origin')
    if stderr.read.include?("Repository not found")
      cleanup = true
    else
      `git pull --rebase`
      # `git fsck --full`
    end
  end

  `rm -rf #{dir}` if cleanup
end
