#!/usr/bin/env ruby
require 'fileutils'
require 'open3'

[Dir.glob('*') + Dir.glob('*/*')].flatten.shuffle.each do |dir|
  next unless File.directory? dir
  Dir.chdir(dir) do
    next unless File.directory?('.git')
    `git checkout master`
    `git remote prune origin`
    `git pull --rebase`
  end
end
