#!/usr/bin/env ruby

Dir.glob('*/*/*').shuffle.each do |dir|
  next unless File.directory? dir
  Dir.chdir(dir) do
    next unless File.directory?('.git')
    puts dir
    `git checkout master`
    `git remote prune origin`
    `git pull --rebase`
    # `git fsck --full`
  end
end
