#!/usr/bin/env ruby
require 'parallel'

Parallel.map(Dir.glob('*/*/*').shuffle) do |dir|
  next unless File.directory? dir

  Dir.chdir(dir) do
    next unless File.directory?('.git')
    puts dir
    `git gc --aggressive --prune`
  end
end
