#!/usr/bin/env ruby
require 'parallel'

Parallel.map(Dir.glob('*/*/*').shuffle) do |dir|
  next if dir =~ /^www\.github\.com/
  next unless File.directory?(dir + '/.git')

  Dir.chdir(dir) do
    puts dir
    `git gc --aggressive --prune`
  end
end
