require "rake"
require "fileutils"

desc 'generate index.html'
task :generate do
  require 'kramdown'
  header = File.read('hsbt.org/src/header.html')
  body = Kramdown::Document.new(File.read('hsbt.org/src/index.md')).to_html
  footer = File.read('hsbt.org/src/footer.html')
  File.open('hsbt.org/dist/index.html', 'w') do |f|
    [header, body, footer].each {|s| f.puts s}
  end
end

desc 'deploy index.html'
task :deploy => [:generate] do
  require 'net/scp'
  Net::SCP.upload!('www.hsbt.org', 'ubuntu', "hsbt.org/dist/index.html", "/home/ubuntu/www/hsbt.org/index.html")
  Net::SCP.upload!('www.hsbt.org', 'ubuntu', "hsbt.org/dist/hsbt.css", "/home/ubuntu/www/hsbt.org/stylesheets/hsbt.css")
end

# NOTE: the `launchctl setenv` LaunchAgents are now generated by
# `mise bootstrap` from toolbox/mise.toml, not here. See that file.
# This task only handles /etc/paths.d until that piece migrates too.
task :push_system_env do
  system "sudo cp toolbox/system/paths /etc/paths.d/paths"
  system "sudo sd 'HOME' #{ENV.fetch('HOME')} /etc/paths.d/paths"
end

task :purge_system_env do
  system "sudo rm /etc/paths.d/paths"
end

RAILS_VERSIONS = {
  "8.1" => "rails81",
  "8.0" => "rails80",
  "7.2" => "rails72",
  "7.1" => "rails71",
  "7.0" => "rails70",
}

namespace :boilerplate do
  desc "regenerate all boilerplate Rails apps with latest patch versions"
  task :update do
    RAILS_VERSIONS.each do |version, dir|
      dest = File.expand_path("boilerplate/#{dir}", __dir__)
      puts "==> Recreating #{dir} (Rails ~> #{version})"

      FileUtils.rm_rf(dest)
      system("gem install rails -v '~> #{version}.0' --no-document", exception: true)
      installed = `gem list -e rails`.match(/rails \(([^)]+)\)/)[1]
      latest = installed.split(", ").select { |v| v.start_with?(version) }.first
      system("rails", "_#{latest}_", "new", dest, exception: true)
      FileUtils.rm_rf(Dir.glob("#{dest}/**/tmp/cache/bootsnap"))

      puts "    #{dir} created"
    end
  end
end
