require "rake"
require "fileutils"

desc 'generate index.html'
task :generate do
  require 'kramdown'
  header = File.read('hsbt.org/src/header.html')
  body = Kramdown::Document.new(File.read('hsbt.org/src/index.md')).to_html
  footer = File.read('hsbt.org/src/footer.html')
  File.open('hsbt.org/dist/index.html', 'w') do |f|
    [header, body, footer].each {|s| f.puts s}
  end
end

desc 'deploy index.html'
task :deploy => [:generate] do
  require 'net/scp'
  Net::SCP.upload!('www.hsbt.org', 'ubuntu', "hsbt.org/dist/index.html", "/home/ubuntu/www/hsbt.org/index.html")
  Net::SCP.upload!('www.hsbt.org', 'ubuntu', "hsbt.org/dist/hsbt.css", "/home/ubuntu/www/hsbt.org/stylesheets/hsbt.css")
end

# NOTE: the `launchctl setenv` LaunchAgents are now generated by
# `mise bootstrap` from toolbox/mise.toml, not here. See that file.
# This task only handles /etc/paths.d until that piece migrates too.
task :push_system_env do
  system "sudo cp toolbox/system/paths /etc/paths.d/paths"
  system "sudo sd 'HOME' #{ENV.fetch('HOME')} /etc/paths.d/paths"
end

task :purge_system_env do
  system "sudo rm /etc/paths.d/paths"
end
