# NOTE: the `launchctl setenv` LaunchAgents are now generated by
# `mise bootstrap` from bootstrap/mise.toml, not here. See that file.
# This task only handles /etc/paths.d until that piece migrates too.
task :push_system_env do
  system "sudo cp bootstrap/system/paths /etc/paths.d/paths"
  system "sudo sd 'HOME' #{ENV.fetch("HOME")} /etc/paths.d/paths"
end

task :purge_system_env do
  system "sudo rm /etc/paths.d/paths"
end
