#!/usr/bin/env ruby
require 'pathname'
require 'parallel'

system "rbenv install 2.3.0-dev --force"

Parallel.map(%w(2.0.0-dev 2.1.0-dev 2.2.0-dev 2.3.0-dev)) do |dev|
  gem_cmd = File.expand_path("~/.anyenv/envs/rbenv/versions/#{dev}/bin/gem")
  system "#{gem_cmd} install rb-readline"
  system "#{gem_cmd} update --system"
  system "yes | #{gem_cmd} update"
  system "yes | #{gem_cmd} cleanup"
end

system `find ~/.anyenv/envs/rbenv/versions/2.3.0-dev -name readline.bundle -delete`
