#!/usr/bin/env ruby
require 'pathname'

Dir.glob(File.expand_path("~/.anyenv/envs/rbenv/versions/*")).each do |v|
  next if v.include? "jruby"

  %w(2.0.0-dev 2.1.0-dev 2.2.0-dev 2.3.0-dev).each do |dev|
    if v.include? dev
      system "rbenv install #{Pathname(v).basename.to_s} --force"
    end
  end

  if v.include?('dev')
    gem_cmd = "#{v}/bin/gem"
    system "#{gem_cmd} update --system"
    system "yes | #{gem_cmd} update"
    system "yes | #{gem_cmd} cleanup"
  end
end
