#!/usr/bin/env ruby

require "rubygems/commands/pristine_command"

gems = Gem::Specification.all.map { |spec|
  [spec.name, spec.version] if spec.platform == RUBY_ENGINE && spec.missing_extensions?
}.compact.uniq

gems.each do |n, v|
  cmd = Gem::Commands::PristineCommand.new
  cmd.options[:args] = [n]
  cmd.options[:version] = v
  cmd.execute
rescue Gem::Ext::BuildError
end
