#!/usr/bin/env ruby

require "rubygems/commands/pristine_command"

Gem::Specification.select { |spec|
  spec.platform == RUBY_ENGINE && spec.missing_extensions?
}.each do |s|
  begin
    puts s.full_name
    cmd = Gem::Commands::PristineCommand.new
    cmd.options[:args] = [s.name]
    cmd.options[:version] = s.version
    cmd.execute
  rescue Gem::Ext::BuildError, Gem::Package::FormatError, Gem::InstallError, Zlib::BufError
  end
end
