#!/usr/bin/env ruby

require "rbconfig"
require "pathname"

gems = Gem::Specification.select { |spec|
  spec.platform == RUBY_ENGINE && !spec.extensions.empty?
}.compact.uniq.map { |spec|
  [spec.name, spec.version]
}

gems.each do |n, v|
  s = Gem::Specification.find_all_by_full_name("#{n}-#{v}").first
  (s.full_require_paths - [s.extension_dir]).each do |path|
    Dir.glob(File.join(path, "**/*")).each do |file|
      if Pathname(file).extname == ".#{RbConfig::CONFIG["DLEXT"]}"
        puts "Deleting #{file}"
        File.delete(file)
      end
    end
  end
end
