#!/usr/bin/env ruby

require "shellwords"
require "fileutils"
require "pathname"

FileUtils.rm_rf "#{ENV["RBENV_ROOT"]}/plugins/rbenv-jit"

system "rbenv global system"

defs = `rbenv install --list`.split.select { |v| v =~ /[0-9]/ }
eol_versions = %w[
  2.6.10
  2.7.8
]
dev_versions = %w[
  3.0
  3.1
  3.2
  3.3
]

eol_versions.each do |v|
  puts "Installing #{v}"
  system "rbenv uninstall -f #{v}"
  additional_cflags = "RUBY_CFLAGS=-Wno-error=implicit-function-declaration" if v == "2.6.10"
  openssl_flag = "--with-openssl-dir=$(brew --prefix openssl@1.1)" if v == "2.7.8"
  system "env #{additional_cflags} RUBY_CONFIGURE_OPTS=\"--disable-install-doc --with-libyaml-dir=$(brew --prefix libyaml) --with-gmp-dir=$(brew --prefix gmp) #{openssl_flag}\" rbenv install -f #{v}"
end

dev_versions.each do |v|
  openssl_version = (v.to_f > 3.0) ? "3" : "1.1"
  puts "Installing #{v}"
  system "rbenv uninstall -f #{v}.0-dev"
  system "env RUBY_CONFIGURE_OPTS=\"--disable-install-doc --with-libyaml-dir=$(brew --prefix libyaml) --with-gmp-dir=$(brew --prefix gmp) --with-openssl-dir=$(brew --prefix openssl@#{openssl_version})\" rbenv install -f #{v}.0-dev"

  Dir.chdir(ENV["RBENV_ROOT"] + "/versions") do
    FileUtils.rm_rf v
    File.symlink(v + ".0-dev", v)
    d = defs.find { |d| d =~ /^#{v}.\d+$/ }
    if d
      latest = d.match(/\d+$/).to_s.to_i
      0.upto(latest) do |i|
        stable = "#{v}.#{i}"
        File.unlink(stable) if File.symlink?(stable)
        File.symlink(v + ".0-dev", stable)
      end
    end
  end
end

(eol_versions << dev_versions.first).each do |v|
  gem_dir = Dir.glob("#{ENV['RBENV_ROOT']}/versions/#{v}/lib/ruby/gems/*").first
  system "env GEM_HOME=#{gem_dir} #{ENV["RBENV_ROOT"]}/versions/#{v}/bin/gem update --system"
end

platforms = %w[jruby truffleruby truffleruby+graalvm]
installed = `rbenv versions`.split("\n").map{ |v| v.split(" ")[0] }
platforms.each do |pf|
  installed.each do |v|
    system "rbenv uninstall -f #{v}" if v =~ Regexp.new(pf.shellescape)
  end
end
platforms.each do |pf|
  puts "Installing #{pf}"
  d = defs.find { |d| d =~ Regexp.new(pf.shellescape) }
  system "rbenv install #{d}"
end

system "rbenv global #{dev_versions.last}.0-dev"

FileUtils.ln_s "#{File.expand_path('~')}/Documents/github.com/hsbt/rbenv-jit", "#{ENV["RBENV_ROOT"]}/plugins/rbenv-jit"
