#!/usr/bin/env ruby

require 'shellwords'
require 'fileutils'
require 'pathname'

system "rbenv global system && rbenv rehash && rbenv shell --unset"

defs = `rbenv install --list`.split.select { |v| v =~ /[0-9]/ }
dev_versions = %w[
  2.7
  3.0
  3.1
  3.2
]

dev_versions.each do |v|
  openssl_version = (v =~ /3\.2/) ? "3" : "1.1"
  system "rbenv uninstall -f #{v}.0-dev"
  system "env RUBY_CONFIGURE_OPTS=\"--disable-install-doc --with-openssl-dir=$(brew --prefix openssl@#{openssl_version})\" rbenv install -f #{v}.0-dev"
  Dir.chdir(ENV["RBENV_ROOT"] + "/versions") do
    File.unlink(v) if File.symlink?(v)
    File.symlink(v + ".0-dev", v)
    d = defs.find { |d| d =~ /^#{v}.\d+$/ }  
    if d
      latest = d.match(/\d+$/).to_s.to_i
      0.upto(latest) do |i|
        stable = "#{v}.#{i}"
        File.unlink(stable) if File.symlink?(stable)
        File.symlink(v + ".0-dev", stable)
      end
    end
  end
end

platforms = %w[jruby] # truffleruby truffleruby+graalvm]
platforms.each do |pf|
  d = defs.find { |d| d =~ Regexp.new(pf.shellescape) }
  system "rbenv uninstall -f #{d} && rbenv install #{d}"
end

system "rbenv global #{dev_versions.last}.0-dev"

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("npm").to_s
system "npm install -g npm"
%w[
  typescript
  babel-cli
  eslint
  yarn
].each {|pkg| system "npm install -g #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("cargo").to_s
%w[
  cargo-update
].each {|pkg| system "cargo install #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("go").to_s
%w[
  github.com/motemen/github-list-starred@latest
  github.com/client9/misspell/cmd/misspell@latest
  github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
  github.com/ramya-rao-a/go-outline@latest
  github.com/cweill/gotests/gotests@latest
  github.com/fatih/gomodifytags@latest
  github.com/josharian/impl@latest
  github.com/haya14busa/goplay/cmd/goplay@latest
  github.com/go-delve/delve/cmd/dlv@latest
  honnef.co/go/tools/cmd/staticcheck@latest
  golang.org/x/tools/gopls@latest
  github.com/google/codesearch/cmd/csearch@latest
  github.com/google/codesearch/cmd/cindex@latest
  github.com/google/codesearch/cmd/cgrep@latest
  github.com/hound-search/hound/cmds/hound@latest
  github.com/hound-search/hound/cmds/houndd@latest
].each {|pkg| system "go install #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("heroku").to_s
%w[
  addons-admin
  apps-table
  buildpacks
  buildpack-registry
  heroku-accounts
  heroku-config
  heroku-pg-extras
  heroku-repo
].each {|pkg| system "heroku plugins:install #{pkg}" }

%w[
  jethrokuan/fzf
  decors/fish-ghq
  evanlucas/fish-kubectl-completions
  rbenv/fish-rbenv
].each {|pkg| system "fisher install #{pkg}" }
