#!/usr/bin/env ruby

require "rubygems/commands/pristine_command"

gems = Gem::Specification.select { |spec|
  spec.platform == RUBY_ENGINE && spec.missing_extensions?
}.compact.uniq.map { |spec|
  [spec.name, spec.version]
}

gems.each do |n, v|
  cmd = Gem::Commands::PristineCommand.new
  cmd.options[:args] = [n]
  cmd.options[:version] = v
  cmd.execute
rescue Gem::Ext::BuildError, Gem::Package::FormatError, Gem::InstallError, Zlib::BufError
end
