#!/usr/bin/env bash

brew upgrade
brew upgrade --cask
brew autoremove
brew cleanup

rbenv update

eval "$(rbenv init -)"

rbenv each gem uninstall openssl psych racc zlib digest strscan stringio pathname --force
rbenv global system
rbenv uninstall -f 3.3.0-dev
env RUBY_CONFIGURE_OPTS="--disable-install-doc --with-openssl-dir=$(brew --prefix openssl) --with-gmp-dir=$(brew --prefix gmp) --with-libyaml-dir=$(brew --prefix libyaml)" rbenv install 3.3.0-dev
rbenv global 3.3.0-dev

gem update
rbenv each dev only-missing-pristine
dev clean-lib-ext
dev gem-shebang-update

go-global-update
cargo install-update -a
