#!/usr/bin/env ruby
require "parallel"

IGNORE_REPOS = %w[
]

Dir.chdir(`ghq root`.chomp) do
  Parallel.map(`ghq list`.split.shuffle) do |dir|
    next if IGNORE_REPOS.any? { |repo| dir.include?(repo) }
    next unless File.directory?(dir + "/.git")

    puts dir

    Dir.chdir(dir) do
      system('git fetch --multiple origin ruby-core --prune --no-tags')
      system('git stash')
      system("git remote show origin | grep 'HEAD branch' | awk '{print $NF}' | xargs git switch")
      system('git pull --rebase --prune')
      system('git submodule update --init --recursive')
      system('git gc --prune')
    end
  end
end
