#!/usr/bin/env bash

brew upgrade
brew upgrade --cask
brew autoremove
brew cleanup

rbenv update

eval "$(rbenv init -)"

rbenv each gem uninstall openssl psych racc zlib digest strscan stringio pathname --force --executables
rbenv global system
rbenv uninstall -f ruby-dev
env RUBY_CONFIGURE_OPTS="--disable-install-doc --with-baseruby=/opt/homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby  --with-openssl-dir=$(brew --prefix openssl) --with-gmp-dir=$(brew --prefix gmp) --with-libyaml-dir=$(brew --prefix libyaml)" rbenv install ruby-dev
rbenv global ruby-dev

gem update
rbenv each dev only-missing-pristine
dev gem-shebang-update

go-global-update
cargo install-update -a
