#!/usr/bin/env ruby

eol_versions = %w[
]
dev_versions = %w[
  3.1
  3.2
  3.3
]

require "shellwords"
require "fileutils"
require "pathname"

system "rbenv global system"

defs = `rbenv install --list`.split.select { |v| v =~ /[0-9]/ }

eol_versions.each do |v|
  puts "Installing #{v}"
  system "rbenv uninstall -f #{v}"
  openssl_flag = "--with-openssl-dir=$(brew --prefix openssl@1.1)" if v == "3.0.7"
  system "env RUBY_CONFIGURE_OPTS=\"--disable-install-doc --with-baseruby=/opt/homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby --with-libyaml-dir=$(brew --prefix libyaml) #{openssl_flag}\" rbenv install -f #{v}"
end

dev_versions.each do |v|
  puts "Installing #{v}"
  system "rbenv uninstall -f #{v}-dev"
  system "brew uninstall gmp" if v == "3.2"
  system "env RUBY_CONFIGURE_OPTS=\"--disable-install-doc --with-baseruby=/opt/homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby --with-libyaml-dir=$(brew --prefix libyaml) --with-openssl-dir=$(brew --prefix openssl@3)\" rbenv install -f #{v}-dev"
  system "brew install gmp" if v == "3.2"

  Dir.chdir(ENV["RBENV_ROOT"] + "/versions") do
    FileUtils.rm_rf v
    File.symlink(v + "-dev", v)
    d = defs.find { |d| d =~ /^#{v}.\d+$/ }
    if d
      latest = d.match(/\d+$/).to_s.to_i
      0.upto(latest) do |i|
        stable = "#{v}.#{i}"
        File.unlink(stable) if File.symlink?(stable)
        File.symlink(v + "-dev", stable)
      end
    end
  end
end

system "rbenv uninstall -f ruby-dev"
system "env RUBY_CONFIGURE_OPTS=\"--disable-install-doc --with-baseruby=/opt/homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby  --with-openssl-dir=$(brew --prefix openssl) --with-gmp-dir=$(brew --prefix gmp) --with-libyaml-dir=$(brew --prefix libyaml)\" rbenv install ruby-dev"

platforms = %w[jruby truffleruby graalvm]
installed = `rbenv versions`.split("\n").map{ |v| v.split(" ")[0] }
platforms.each do |pf|
  installed.each do |v|
    system "rbenv uninstall -f #{v}" if v =~ Regexp.new(pf.shellescape)
  end
end
platforms.each do |pf|
  puts "Installing #{pf}"
  d = defs.find { |d| d =~ Regexp.new(pf) }
  system "rbenv install #{d}"
end

system "rbenv global ruby-dev"
