#!/usr/bin/env ruby
require "parallel"
require "pathname"

IGNORE_REPOS = %w[]

Dir.chdir(File.expand_path(ENV['GIT_GOGET_ROOT'])) do
  Parallel.map(Dir.glob("*/*/*")) do |dir|
    next if IGNORE_REPOS.any? { |repo| dir.include?(repo) }
    next unless File.directory?(dir + "/.git")

    puts dir

    Dir.chdir(dir) do
      system("git fetch --multiple origin ruby-core --prune --no-tags")
      system("git stash")
      system("git remote show origin | grep 'HEAD branch' | awk '{print $NF}' | xargs git switch")
      system("git pull --rebase --prune")
      system("git submodule update --init --recursive")
      system("git gc --prune")
    end
  end
end

Dir.chdir(File.expand_path(ENV['GIT_GOGET_ROOT']).join("github.com/ruby/ruby")) do
  system("ruby tool/sync_default_gems.rb up")
end
