#!/usr/bin/env bash

mise use -g ruby@3.4-dev
gem update
gem uninstall openssl psych zlib digest strscan stringio pathname etc date --force --executables

for v in 3.1 3.2 3.3 3.4 ruby; do
    mise use -g ruby@$v-dev
    dev-only-missing-pristine
done

mise use -g ruby@ruby-dev
gem-ext-cleaner
