#!/usr/bin/env ruby

if RUBY_VERSION < "2.7"
  gem "parallel", "1.2.4"
end
require "parallel"

require "rubygems/installer"

specs = Gem::Specification.select do |spec|
  spec.platform == RUBY_ENGINE && spec.respond_to?(:missing_extensions?) && spec.missing_extensions?
end

specs = specs.group_by { |s| [s.name, s.version] }.map do |_, gems|
  non_default_specs = gems.select { |s| !s.default_gem? }
  if non_default_specs.empty?
    gems
  else
    non_default_specs
  end
end.flatten(1).shuffle

Parallel.map(specs, :in_threads => 4) do |spec|
  begin
    puts spec.full_name
    installer_options = {
      wrappers: true,
      force: true,
      install_dir: spec.base_dir,
      env_shebang: true,
      build_args: spec.build_args,
    }
    installer = Gem::Installer.at(spec.cache_file, installer_options)
    installer.install
    puts "Installed #{spec.full_name} to #{spec.base_dir}"
  rescue Gem::Ext::BuildError, Gem::Package::FormatError, Gem::InstallError, Zlib::BufError, NameError
  end
end
