#!/usr/bin/env ruby

Dir.glob(ENV["GEM_HOME"] + "/bin/*") do |exe|
  %w[hsbt hiroshi.shibata].each do |u|
    %w[3.1 3.2 3.3 3.4 ruby].each do |v|
      system("gsed -i '1s|^#!/Users/#{u}/.local/share/mise/installs/ruby/#{v}-dev/bin/ruby|#!/usr/bin/env ruby|' #{exe}")
    end
  end
end
