#!/usr/bin/env bash

brew upgrade
brew upgrade --cask
brew autoremove
brew cleanup
go-global-update
rustup update
cargo install-update -a
mise upgrade

for v in ruby-dev 3.4 3.3 3.2 3.1; do
  MISE_RUBY_VERSION=$v gem uninstall openssl psych zlib digest strscan stringio pathname --force --executables
done

mise use ruby@3.4-dev
mise uninstall ruby@ruby-dev
mise install ruby@ruby-dev
mise use ruby@ruby-dev

export MISE_RUBY_VERSION=ruby-dev
unset GEM_HOME
gem list --no-versions | xargs gem uninstall --force
export GEM_HOME=~/.local/share/gem
unset MISE_RUBY_VERSION

curl -s https://stdgems.org/bundled_gems.json | jq -r '.gems[].gem' | xargs -n1 gem install

MISE_RUBY_VERSION=3.4 gem update

for v in ruby-dev 3.4 3.3 3.2 3.1; do
  MISE_RUBY_VERSION=$v gem uninstall openssl psych zlib digest strscan stringio pathname --force --executables
done

for v in 3.1 3.2 3.3 3.4 ruby-dev; do
  MISE_RUBY_VERSION=$v dev-only-missing-pristine
done
dev-gem-shebang-update
