#!/usr/bin/env ruby

Dir.glob(ENV["GEM_HOME"] + "/bin/*") do |exe|
  %w[hsbt hiroshi.shibata].each do |u|
    system("gsed -i '1s|^#!/Users/hsbt/.local/share/rbenv/versions/ruby-dev/bin/ruby|#!/usr/bin/env ruby|' #{exe}")
    %w[3.1 3.2 3.3].each do |v|
      system("gsed -i '1s|^#!/Users/hsbt/.local/share/rbenv/versions/#{v}-dev/bin/ruby|#!/usr/bin/env ruby|' #{exe}")
    end
  end
end
