#!/usr/bin/env ruby

dev_versions = %w[
  3.1
  3.2
  3.3
  3.4
]

require "shellwords"
require "fileutils"
require "json"

defs = `mise ls-remote ruby`.split

dev_versions.each do |v|
  system "mise uninstall ruby@#{v}-dev"
  system "mise i ruby@#{v}-dev"

  Dir.chdir(ENV["HOME"] + "/.local/share/mise/installs/ruby") do
    FileUtils.rm_rf v
    File.symlink(v + "-dev", v)
    d = defs.select { |d| d =~ /^#{v}.\d+$/ }.last
    if d
      latest = d.match(/\d+$/).to_s.to_i
      0.upto(latest) do |i|
        stable = "#{v}.#{i}"
        File.unlink(stable) if File.symlink?(stable)
        File.symlink(v + "-dev", stable)
      end
    end
  end
end

system "mise uninstall ruby@ruby-dev"
system "MISE_RUBY_VERSION=3.4-dev mise i ruby@ruby-dev"

platforms = %w[jruby truffleruby.graalvm truffleruby-]
installed = JSON.parse(`mise ls ruby -J`).map{|r| r["version"] }
platforms.each do |pf|
  installed.each do |v|
    system "mise uninstall ruby@#{v}" if v =~ Regexp.new(pf)
  end
  d = defs.select { |d| d =~ Regexp.new("^#{pf}") }.last
  system "mise i ruby@#{d}"
end
