#!/usr/bin/env ruby

require "fileutils"
require "pathname"

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("npm").to_s
system "npm install -g npm"
%w[
  typescript
  babel-cli
  eslint
  yarn
  @cyclonedx/cdxgen
  heroku@10.1.0
].each { |pkg| system "npm install -g #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("cargo").to_s
%w[
  cargo-update
  lsd
  bat
  ripgrep
  fd-find
  grex
  du-dust
  zoxide
  tealdeer
  hexyl
  procs
  sd
  ripgrep_all
  git-delta
  xh
  spacer
  skim
  sccache
  coreutils
  findutils
  hyperfine
  tokei
  mise
  hk
  wrkflw
].each { |pkg| system "cargo install --locked #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("go").to_s
%w[
  github.com/Gelio/go-global-update@latest
  github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
  github.com/ramya-rao-a/go-outline@latest
  github.com/cweill/gotests/gotests@latest
  github.com/fatih/gomodifytags@latest
  github.com/josharian/impl@latest
  github.com/haya14busa/goplay/cmd/goplay@latest
  github.com/go-delve/delve/cmd/dlv@latest
  honnef.co/go/tools/cmd/staticcheck@latest
  golang.org/x/tools/gopls@latest
  github.com/client9/misspell/cmd/misspell@latest
  github.com/rhysd/actionlint/cmd/actionlint@latest
  github.com/google/codesearch/cmd/csearch@latest
  github.com/google/codesearch/cmd/cindex@latest
  github.com/google/codesearch/cmd/cgrep@latest
  github.com/google/osv-scanner/cmd/osv-scanner@v1
  github.com/google/yamlfmt/cmd/yamlfmt@latest
  github.com/mikefarah/yq/v4@latest
  github.com/antonmedv/fx@latest
  github.com/tomnomnom/gron@latest
  github.com/DarthSim/overmind/v2@latest
  github.com/dependabot/cli/cmd/dependabot@latest
  github.com/charmbracelet/vhs@latest
  golang.org/x/vuln/cmd/govulncheck@latest
  github.com/traefik/yaegi/cmd/yaegi@latest
  github.com/mindersec/minder/cmd/cli@latest
  github.com/bomctl/bomctl@latest
  github.com/ossf/scorecard@latest
  github.com/openvex/vexctl@latest
  github.com/google/go-containerregistry/cmd/crane@latest
  github.com/devops-kung-fu/bomber@latest
  github.com/aquasecurity/trivy/cmd/trivy@latest
  github.com/anchore/syft/cmd/syft@latest
  github.com/sinclairtarget/git-who@latest
  github.com/peak/s5cmd/v2@master
].each { |pkg| system "go install #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("heroku").to_s
%w[
  addons-admin
  apps-table
  buildpacks
  buildpack-registry
  heroku-accounts
  heroku-config
  heroku-pg-extras
  heroku-builds
  heroku-slugs
  heroku-repo
  heroku-releases-retry
  @heroku-cli/plugin-free
  @heroku-cli/plugin-api
].each { |pkg| system "heroku plugins:install #{pkg}" }

%w[
  evanlucas/fish-kubectl-completions
  0rax/fish-bd
  2m/fish-history-merge
].each { |pkg| system "fisher install #{pkg}" }
system "curl -L https://raw.github.com/skim-rs/skim/master/shell/key-bindings.fish --create-dirs -o ~/.config/fish/conf.d/sk_key_bindings.fish"

%w[
  github/gh-copilot
  advanced-security/gh-sbom
  mislav/gh-cp
  github/gh-actions-importer
].each { |pkg| system "gh extension install #{pkg}" }
