#!/usr/bin/env ruby

if RUBY_VERSION < "2.7"
  gem "parallel", "1.2.4"
end
require "parallel"

require "rubygems/commands/pristine_command"

specs = Gem::Specification.select do |spec|
  spec.platform == RUBY_ENGINE && spec.missing_extensions?
end

specs = specs.group_by { |s| [s.name, s.version] }.map do |_, gems|
  non_default_specs = gems.select { |s| !s.default_gem? }
  if non_default_specs.empty?
    gems
  else
    non_default_specs
  end.map{|s| [s.full_name, s.name, s.version] }
end.flatten(1).shuffle

Parallel.map(specs, :in_threads => 4) do |full_name, name, version|
  begin
    puts full_name
    cmd = Gem::Commands::PristineCommand.new
    cmd.options[:args] = [name]
    cmd.options[:version] = version
    cmd.execute
  rescue Gem::Ext::BuildError, Gem::Package::FormatError, Gem::InstallError, Zlib::BufError, NameError
  end
end
