#!/usr/bin/env bash

brew upgrade
brew upgrade --cask
brew autoremove
brew cleanup

mise upgrade
if ls -d asdf-dart.* 2>/dev/null | grep -q .; then
    ../../labs/dart-sdk-installer/install-dart.sh
    rm -rf asdf-dart.*
fi

go-global-update
rustup update
cargo install-update -a

mise uninstall ruby@ruby-dev
mise use -g ruby@ruby-dev

unset GEM_HOME
gem list --no-versions | xargs gem uninstall --force
export GEM_HOME=~/.local/share/gem

cd "$GIT_GOGET_ROOT/github.com/ruby/ruby"
ruby tool/sync_default_gems.rb up
