export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/Library/Caches"
export KREW_ROOT="$XDG_DATA_HOME/krew"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PATH="$XDG_DATA_HOME/mise/shims:$PATH"
