inquiries_tables:
  - database:
      adapter: mysql2
      host: localhost
      database: whispered_test
      username: root
      password:
      reconnect: true
    name: inquiries
    display_columns:
      - name
      - email
      - message
    created_at: create_date
members:
  - hsbt
github:
  key: 
  secret:
