;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-set-rectangle-mark
        cua-toggle-rectangle-mark
        replace-regexp
        seq-home
        ))

(setq mc/cmds-to-run-once
      '(
        cua-clear-rectangle-mark
        cua-delete-char-rectangle
        cua-insert-char-rectangle
        seq-end
        ))
