# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"

  config.vm.synced_folder "../../../../github.com", "/vagrant/github.com"

  config.vm.provision :itamae do |config|
    config.recipes = ['../recipe_yum.rb']
    config.json = '../node.json'
  end

  config.vm.provision :shell, :path => "../scripts/install_libmemcached_centos7.sh"
  config.vm.provision :shell, :path => "../scripts/build_mruby.sh"
end
