# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box"

  config.vm.synced_folder "../../../../github.com", "/vagrant/github.com"
  config.vm.synced_folder "../../../../localhost", "/vagrant/localhost"

  config.vm.provision :itamae do |config|
    config.recipes = ['../recipe.rb']
    config.json = '../node.json'
  end
end
