source :rubygems

gem 'rails'
gem 'mysql2'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'
gem 'settingslogic'
gem 'carrierwave'
gem "fog", '~> 1.3.1'
