#!/usr/bin/env bash

rbenv update
pyenv update
nodenv update

eval "$(rbenv init -)"

rbenv shell --unset

brew upgrade
brew cask upgrade

rbenv global system
rbenv uninstall -f 2.7.0-dev
rbenv install 2.7.0-dev
rbenv global 2.7.0-dev

gem update

rbenv shell 2.4
~/Documents/github.com/hsbt/tools/libexec/all-pristine
rbenv shell 2.5
~/Documents/github.com/hsbt/tools/libexec/all-pristine
rbenv shell 2.6
~/Documents/github.com/hsbt/tools/libexec/all-pristine
rbenv shell 2.7
~/Documents/github.com/hsbt/tools/libexec/all-pristine

~/Documents/github.com/hsbt/tools/libexec/gem-shebang

rbenv shell --unset
