#!/usr/bin/env bash

brew upgrade
brew upgrade --cask

rbenv update

eval "$(rbenv init -)"

rbenv shell --unset

rbenv global system
rbenv uninstall -f 3.0.0-dev
rbenv install 3.0.0-dev
rbenv global 3.0.0-dev

rbenv shell 3.0.0-dev
gem update
gem uninstall --force openssl zlib psych

rbenv shell 2.5
dev all-pristine
rbenv shell 2.6
dev all-pristine
rbenv shell 2.7
dev all-pristine
rbenv shell 3.0
dev all-pristine

dev gem-shebang-update

rbenv shell --unset

pyenv update
pip install -U pip
pip install -U wheel
pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U

nodenv update
npm update -g

rustup update
cargo install-update -a
