#!/usr/bin/env ruby

require "fileutils"
require "pathname"

require "parallel"

path = ARGV[0] || Dir.pwd

Parallel.each(Dir.glob(File.join(File.realpath(path), "**/*.jp*")), in_threads: 4) do |f|
  puts f
  o = f + ".new"
  next if File.exist?(o)
  `guetzli #{f} #{o}`
  if File.exist?(o)
    FileUtils.cp o, f
    FileUtils.rm o
  end
end
