#!/usr/bin/env ruby
require "parallel"

Dir.chdir(`ghq root`.chomp) do
  Parallel.map(`ghq list`.split.shuffle) do |dir|
    next unless File.directory?(dir + "/.git")
    next if /github\.com\/ruby/.match?(dir)

    puts dir

    Dir.chdir(dir) do
      system('git fetch --all --prune')
      system('git pull --rebase --prune')
      system('git submodule update --init --recursive')
      system('git gc --prune')
    end
  end
end
