#!/usr/bin/env ruby

require 'shellwords'
require 'fileutils'
require 'pathname'

system "rbenv global system && rbenv rehash && rbenv shell --unset"

defs = `rbenv install --list`.split.select { |v| v =~ /[0-9]/ }
dev_versions = %w[
  2.7
  3.0
  3.1
  3.2
]

dev_versions.each do |v|
  system "rbenv uninstall -f #{v}.0-dev && rbenv install -f #{v}.0-dev"
  Dir.chdir(ENV["RBENV_ROOT"] + "/versions") do
    File.unlink(v) if File.symlink?(v)
    File.symlink(v + ".0-dev", v)
    d = defs.find { |d| d =~ /^#{v}.\d+$/ }  
    if d
      latest = d.match(/\d+$/).to_s.to_i
      0.upto(latest) do |i|
        stable = "#{v}.#{i}"
        File.unlink(stable) if File.symlink?(stable)
        File.symlink(v + ".0-dev", stable)
      end
    end
  end
end

platforms = %w[jruby truffleruby truffleruby+graalvm]
platforms.each do |pf|
  d = defs.find { |d| d =~ Regexp.new(pf.shellescape) }
  system "rbenv uninstall -f #{d} && rbenv install #{d}"
end

system "rbenv global #{dev_versions.last}.0-dev"

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("npm").to_s
system "npm install -g npm"
%w[
  typescript
  babel-cli
  eslint
  yarn
].each {|pkg| system "npm install -g #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("cargo").to_s
%w[
  cargo-update
].each {|pkg| system "cargo install #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("go").to_s
%w[
  github.com/motemen/github-list-starred
  github.com/client9/misspell/cmd/misspell
  github.com/google/codesearch/cmd/...
  github.com/uudashr/gopkgs/v2/cmd/gopkgs
  github.com/ramya-rao-a/go-outline
  github.com/cweill/gotests/gotests
  github.com/fatih/gomodifytags
  github.com/josharian/impl
  github.com/haya14busa/goplay/cmd/goplay
  github.com/go-delve/delve/cmd/dlv
  github.com/go-delve/delve/cmd/dlv@master
  honnef.co/go/tools/cmd/staticcheck
  golang.org/x/tools/gopls
].each {|pkg| system "go install #{pkg}" }

FileUtils.rm_rf Pathname(ENV["XDG_DATA_HOME"]).join("heroku").to_s
%w[
  heroku-accounts
  heroku-pg-extras
  heroku-repo
  heroku-config
  apps-table
].each {|pkg| system "heroku plugins:install #{pkg}" }
