#!/usr/bin/env ruby

defs = `rbenv install --list`.split.select { |v| v =~ /[0-9]/ }
versions = %w[2.4 2.5 2.6 2.7]

system "rbenv global system"

versions.each do |v|
  system "rbenv uninstall -f #{v}.0-dev && rbenv install -f #{v}.0-dev"
  Dir.chdir(ENV["RBENV_ROOT"] + "/versions") do
    File.unlink v if File.exist?(v)
    File.symlink(v + ".0-dev", v)
    defs.select { |d| d =~ /^#{v}.\d+$/ }.each do |stable|
      File.unlink stable if File.exist?(stable)
      File.symlink(v + ".0-dev", stable)
    end
  end
end

platforms = %w[jruby truffleruby]

platforms.each do |pf|
  d = defs.select { |d| d =~ /#{pf}/ }.max_by { |v| v = v.gsub(/-rc/, ".").gsub(/[a-z\-]/, ""); Gem::Version.new(v) }
  system "rbenv uninstall -f #{d} && rbenv install #{d}"
end

system "rbenv global #{versions.last}.0-dev"

versions = %w[3.7 3.8]

system "pyenv global system"

versions.each do |v|
  system "pyenv uninstall -f #{v}-dev"
  system "env SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14 pyenv install #{v}-dev"
end

system "pyenv global #{versions.first}-dev"
system "pip install pipenv tldr pylint python-openstackclient jupyter notebook pandas bokeh matplotlib"

versions = %w[12]

system "nodenv global system"

versions.each do |v|
  system "nodenv uninstall -f #{v}.x-next"
  system "nodenv install #{v}.x-next"
end
system "nodenv global 12.x-next"
