#!/usr/bin/env ruby

require 'shellwords'
require 'fileutils'
require 'pathname'

system "brew uninstall bison"
system "brew uninstall autoconf --ignore-dependencies"
system "brew install shopify/shopify/autoconf@2.69"

system "rbenv shell --unset && rbenv global system"
defs = `rbenv install --list`.split.select { |v| v =~ /[0-9]/ }

%w[
  2.5.9
  2.6.7
].each {|v| system "rbenv uninstall -f #{v} && CFLAGS='-Wno-error=implicit-function-declaration' rbenv install -f #{v}" }

dev_versions = %w[
  3.1
  3.0
  2.7
]

dev_versions.each do |v|
  system "rbenv uninstall -f #{v}.0-dev && rbenv install -f #{v}.0-dev"
  Dir.chdir(ENV["RBENV_ROOT"] + "/versions") do
    FileUtils.rm_rf(v) if File.exist?(v)
    File.symlink(v + ".0-dev", v)
    d = defs.find { |d| d =~ /^#{v}.\d+$/ }  
    if d
      latest = d.match(/\d+$/).to_s.to_i
      0.upto(latest) do |i|
        stable = "#{v}.#{i}"
        File.unlink stable if File.exist?(stable)
        File.symlink(v + ".0-dev", stable)
      end
    end
  end
end
system "brew uninstall shopify/shopify/autoconf@2.69 --ignore-dependencies"
system "brew install bison autoconf"
platforms = %w[jruby truffleruby truffleruby+graalvm]
platforms.each do |pf|
  d = defs.find { |d| d =~ Regexp.new(pf.shellescape) }
  system "rbenv uninstall -f #{d} && rbenv install #{d}"
end
system "rbenv global #{dev_versions.first}.0-dev"

FileUtils.rm_rf Pathname.join(ENV["XDG_DATA_HOME"], "npm").to_s
system "npm install -g npm"
%w[
  typescript
  babel-cli
  eslint
  yarn
].each {|pkg| system "npm install -g #{pkg}" }

FileUtils.rm_rf Pathname.join(ENV["XDG_DATA_HOME"], "cargo").to_s
%w[
  install-update
].each {|pkg| system "cargo install #{pkg}" }

FileUtils.rm_rf Pathname.join(ENV["XDG_DATA_HOME"], "go").to_s
%w[
  github.com/motemen/github-list-starred
  github.com/client9/misspell/cmd/misspell
  github.com/google/codesearch/cmd/...
].each {|pkg| system "go get -u #{pkg}" }

FileUtils.rm_rf Pathname.join(ENV["XDG_DATA_HOME"], "heroku").to_s
%w[
  heroku-accounts
  heroku-pg-extras
  heroku-repo
  apps-table
].each {|pkg| system "heroku plugins:install #{pkg}" }
