#!/usr/bin/env bash

brew upgrade
brew upgrade --cask

rbenv update

eval "$(rbenv init -)"

rbenv global system
rbenv uninstall -f 3.2.0-dev && rbenv install 3.2.0-dev
rbenv global 3.2.0-dev

dev gem-shebang-update
