#!/usr/bin/env ruby

require "slack-ruby-client"

Slack.configure { |config| config.token = ENV["SLACK_API_TOKEN"] }
client = Slack::Web::Client.new
client.auth_test

uid = "U03NB3174"
display_name = "hsbt"

if ARGV[0] == "on"
  display_name += "-#{Time.now.strftime("%m%d")}休暇"
end

client.users_profile_set({user: uid, profile: {display_name: display_name}.to_json})
