#!/usr/bin/env ruby
require 'parallel'

Parallel.map(Dir.glob('*/*/*').shuffle) do |dir|
  next unless File.directory?(dir + '/.git')
  Dir.chdir(dir) { puts dir; `git fetch --all`; `git gc --prune`}
end
