#!/usr/bin/env ruby
require "parallel"

Dir.chdir(`ghq root`.chomp) do
  Parallel.map(`ghq list`.split.shuffle) do |dir|
    next unless File.directory?(dir + "/.git")
    Dir.chdir(dir) { puts dir; `git fetch --all`; `git gc --prune`; } # `git pull --ff-only`}
  end
end
