#!/usr/bin/env ruby

histories = File.readlines(File.expand_path(ENV["HISTFILE"]))

gogets = histories.map { |history|
  
    cmd = history.split(";")[1]&.chomp
    # only git.example.com, github.com, golang.org, google.golang.org etc.
    cmd.downcase if cmd =~ /^go get -u [git|go]/
  rescue ArgumentError => e
    next
  
}.compact.sort.uniq

gogets.each do |cmd|
  if cmd =~ /go get -u (.*)/
    puts " Upgrading: #{$1}"
    `#{cmd}`
  end
end
