source :rubygems

gem 'rails'
gem 'jquery-rails'
gem 'twitter'

platform :jruby do
  gem 'therubyrhino'
  gem 'get_back'

  group :production do
    gem 'activerecord-jdbcpostgresql-adapter'
  end

  group :development, :test do
    gem 'activerecord-jdbcsqlite3-adapter'
  end
end

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development, :test do
  gem 'rspec-rails'
end
