source :rubygems

gem 'rails'

platform :jruby do
  gem 'activerecord-jdbc-adapter', require: false
  gem 'therubyrhino'
  gem 'get_back'

  group :production do
    gem 'jdbc-postgres'
  end

  group :development, :test do
    gem 'jdbc-sqlite3'
  end
end

gem 'jquery-rails'
gem 'twitter', '2.0.2'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development, :test do
  gem 'rspec-rails'
end
