source :rubygems

gem 'rails'
gem 'jquery-rails'

gem 'trinidad'
gem 'trinidad_diagnostics_extension'
gem 'trinidad_scheduler_extension'
gem 'trinidad_worker_extension'
gem 'resque'

gem 'twitter', '~> 2.0.2'

platform :jruby do
  gem 'therubyrhino'
  gem 'get_back'

  group :production do
    gem 'activerecord-jdbcpostgresql-adapter'
  end

  group :development, :test do
    gem 'activerecord-jdbcsqlite3-adapter'
  end
end

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development, :test do
  gem 'rspec-rails'
end

group :deploy do
  gem "net-ssh", require: "net/ssh"
  gem "net-scp", require: "net/scp"
  gem "warbler"
end
