bindkey -e

setopt extended_glob
setopt no_beep
setopt ignore_eof
setopt no_flow_control
setopt interactive_comments
setopt print_eight_bit
setopt long_list_jobs
setopt numeric_glob_sort
setopt magic_equal_subst

autoload zmv
alias zmv='noglob zmv'

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' verbose yes

export REPORTTIME=3
