export PATH=$PATH:/usr/X11/bin:/usr/texbin
export SUDO_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HOME/.homebrew/lib:$DROPBOX/misc/oracle
export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib:/usr/lib/:/usr/X11R6/lib:$DYLD_LIBRARY_PATH
