# Environment
export LC_CTYPE=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export OUTPUT_CHARSET=UTF-8
export ARCHFLAGS="-arch x86_64"
export EDITOR="vim"

export DROPBOX=$HOME/Dropbox
export GISTY_DIR=$DROPBOX/dev/gists
export RUBYMOTION_ANDROID_SDK=$HOME/.rubymotion-android/sdk
export RUBYMOTION_ANDROID_NDK=$HOME/.rubymotion-android/ndk

source $DROPBOX/config/github.token

export MYSQL_HISTFILE=$DROPBOX/config/history.dotfiles/dot.mysql_history
export MYSQL_PS1='\u@\h[\d]> '

# not open editor when `git pull --rebase`
export GIT_MERGE_AUTOEDIT=no
# dn not use third party CDN
export RUBY_BUILD_SKIP_MIRROR=1
