# Environment
export LC_CTYPE=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export OUTPUT_CHARSET=UTF-8
export ARCHFLAGS="-arch x86_64"
export EDITOR="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient"
export DROPBOX=$HOME/Dropbox

source ~/.zsh.d/gisty
