umask 022
bindkey -e

fpath=(~/.zsh.d/zsh-git-escape-magic ~/.zsh.d/zsh-manydots-magic /usr/local/share/zsh/functions $fpath)

setopt always_last_prompt
setopt auto_list
setopt auto_menu
setopt auto_cd
setopt auto_param_keys
setopt auto_name_dirs
setopt auto_remove_slash
setopt cdable_vars
setopt correct
setopt extended_glob
setopt interactive_comments
setopt list_packed
setopt list_types
setopt magic_equal_subst
setopt prompt_subst
setopt print_eight_bit
setopt numeric_glob_sort
setopt rm_star_silent
setopt sun_keyboard_hack
setopt sh_word_split
setopt zle
setopt long_list_jobs
setopt ignore_eof
setopt no_flow_control
setopt no_beep

zmodload zsh/files
autoload zmv
alias zmv='noglob zmv'

source ~/.zsh.d/antigen/antigen.zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions src
antigen apply
autoload -Uz git-escape-magic
git-escape-magic
autoload -Uz manydots-magic
manydots-magic

autoload colors; colors
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

autoload -U compinit
compinit -d /tmp/$USER.zcompdump
zstyle ':completion:*:default' menu select=1
zstyle ':completion:*:sudo:*' command-path
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' verbose yes
zstyle ':completion:sudo:*' environ PATH="$SUDO_PATH:$PATH"

setopt extended_history
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_save_nodups
setopt hist_reduce_blanks
setopt inc_append_history

HISTFILE=$DROPBOX/config/history.dotfiles/dot.zsh-history
HISTSIZE=10000000
SAVEHIST=$HISTSIZE

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

autoload -Uz is-at-least
export _Z_CMD=j
export _Z_DATA=$DROPBOX/config/history.dotfiles/dot.$USER.z
. ~/.zsh.d/z/z.sh

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn hg
zstyle ':vcs_info:*' formats '[%b]'
zstyle ':vcs_info:*' actionformats '[%b] (%a)'
precmd() {
  psvar=()
  LANG=en_US.UTF-8 vcs_info
  [[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_ $(git rev-parse --short HEAD 2>/dev/null)"
  psvar[2]=`rbenv version-name`
  [[ -e $PWD/.git/refs/stash ]] && psvar[3]="($(git stash list 2>/dev/null | wc -l))"
}
PROMPT=$'[%{$fg[magenta]%}%n%{$reset_color%}@%{$fg[red]%}%M%{$reset_color%}] %{$fg[cyan]%}%d %1(V|%F{green}%1v%3(V| - %3v|)%f |)%2(V|%F{red}(%2v%)%f|)\n%{$fg[yellow]%}%#%{$reset_color%} '
RPROMPT=''

export PATH="$HOME/.anyenv/bin:$PATH"
eval "$(anyenv init -)"
RUBYOPT="-W"
MAKEOPTS="-j4"
CONFIGURE_OPTS="--disable-install-doc"
PERL_RL=Caroline
SBT_OPTS="-XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
REPORTTIME=3

export GOPATH=~/.go
export PATH=$GOPATH/bin:$PATH

export PATH="/usr/local/google-cloud-sdk/bin:$PATH"
export CLOUDSDK_PYTHON=/usr/bin/python
source '/usr/local/google-cloud-sdk/completion.zsh.inc'

[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh
export PATH="$HOME/Documents/github.com/hsbt/scripts:$PATH"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
export PATH="/Applications/calibre.app/Contents/MacOS:$PATH"

typeset -U path PATH
path=(
    # allow directories only (-/)
    # reject world-writable directories (^W)
    $path(N-/^W)
)

zle -N peco-src
bindkey '^s' peco-src

source ~/.zsh.d/functions
source ~/.zsh.d/aliases
