[tools]
aws-cli = "latest"
dart = "latest"
deno = "latest"
elasticsearch = "latest"
elixir = "latest"
gcloud = "latest"
go = "latest"
heroku = "latest"
java = "latest"
mysql = "latest"
node = "latest"
