[tools]
aws-cli = "latest"
bun = "latest"
dart = "latest"
deno = "latest"
elasticsearch = "latest"
elixir = "latest"
gcloud = "latest"
go = "latest"
java = "latest"
mysql = "latest"
node = "latest"
ruby = "ruby-dev"
terraform = "latest"

[env]
_.path = [
  "{{env.GEM_HOME}}/bin",
  "{{env.XDG_DATA_HOME}}/npm/bin",
  "{{env.KREW_ROOT}}/bin",
  "{{env.HOME}}/.local/bin"
]
