# from https://github.com/gofiber/swagger/blob/main/.github/workflows/dependabot_automerge.yml
name: Dependabot auto-merge
on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
      - name: Wait for status checks
        id: wait_for_status
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: "Analyze (ruby)"
      - name: Auto-merge for Dependabot PRs
        uses: pascalgn/automerge-action@v0.4.0
        if: ${{ steps.wait_for_status.outputs.status == 'success' && (steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch') }}
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
