name: rss-to-twitter
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  rss_to_twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: azu/rss-to-twitter@v1
        with:
          RSS_URL: "https://feeds.pinboard.in/rss/secret:3be06bca0fbad88162d9/u:hsbt/"
          TWEET_TEMPLATE: 'Pinboard: "%title%" %url%'
          UPDATE_WITHIN_MINUTES: 15
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      - uses: azu/rss-to-twitter@v1
        with:
          RSS_URL: "https://www.hsbt.org/diary/no_comments.rdf"
          TWEET_TEMPLATE: '日記: "%title%" %url%'
          UPDATE_WITHIN_MINUTES: 15
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
