name: ruby_versions

on:
  workflow_call:
    inputs:
      engine:
        description: "The type of Ruby engine"
        default: "all"
        type: string
      versions:
        description: "Additional Ruby versions"
        default: "[]"
        type: string
      min_version:
        description: "Minimum Ruby version"
        type: number
    outputs:
      versions:
        description: "Ruby versions"
        value: ${{ jobs.ruby_versions.outputs.versions }}

jobs:
  ruby_versions:
    name: Generate Ruby versions
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.value }}
    steps:
      - id: versions
        run: |
          curl -s "https://cache.ruby-lang.org/pub/misc/ci_versions/$ENGINE.json" -o ci_versions.json
          ruby -rjson -e "min = JSON.parse(File.read('ci_versions.json')).sort.first; \
          if $MIN_VERSION > 1.8; p $MIN_VERSION.step(by: 0.1, to: min.to_f).map{|v| t = v.round(1).to_s; t unless ["2.8", "2.9"].include?(t) }.compact[...-1]; else; p []; end;" > versions
          versions=$(cat ci_versions.json | jq -c ". + $VERSIONS" | jq -c ". + $(cat versions)" | jq -c "sort")
          echo "value=${versions}" >> $GITHUB_OUTPUT
        env:
          ENGINE: ${{ inputs.engine }}
          VERSIONS: ${{ inputs.versions }}
          MIN_VERSION: ${{ inputs.min_version }}
