on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: windows-11-arm
    steps:
      - name: Run tests
        run: |
          dir "C:\msys64"
          dir "C:\Program Files\"
          dir "C:\Program Files\Microsoft Visual Studio\"
          dir "C:\Program Files\Microsoft Visual Studio\2022"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\"
