name: WSL

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Install or update WSL
        uses: Ubuntu/WSL/.github/actions/wsl-install@main
        with:
          distro: Ubuntu-24.04

      - name: Check out the repository
        uses: Ubuntu/WSL/.github/actions/wsl-checkout@main
        with:
         distro: Ubuntu-24.04
         working-dir: /tmp/github/
         submodules: true

      - name: Install dependencies
        uses: Ubuntu/WSL/.github/actions/wsl-bash@main
        with:
         distro: Ubuntu-24.04
         working-dir: /tmp/github/
         exec: |
             DEBIAN_FRONTEND=noninteractive sudo apt update
             DEBIAN_FRONTEND=noninteractive sudo apt install -y build-essential
             uname -a
