source "https://rubygems.org"

gem 'mina'
gem 'rake'
gem 'roadworker', '~> 0.5.10'
gem 'kramdown'
gem 'sassc'
gem 'net-scp'
gem 'ed25519'
gem 'rbnacl-libsodium'
gem 'rbnacl', '< 8.0'
gem 'bcrypt_pbkdf'
