desc "generate index.html"
task :generate do
  require "kramdown"
  header = File.read("src/header.html")
  body = Kramdown::Document.new(File.read("src/index.md")).to_html
  footer = File.read("src/footer.html")
  File.open("dist/index.html", "w") do |f|
    [header, body, footer].each { |s| f.puts s }
  end
end

desc "deploy index.html"
task deploy: [:generate] do
  require "net/scp"
  Net::SCP.upload!("www.hsbt.org", "ubuntu", "dist/index.html", "/home/ubuntu/www/hsbt.org/index.html")
  Net::SCP.upload!("www.hsbt.org", "ubuntu", "dist/hsbt.css", "/home/ubuntu/www/hsbt.org/stylesheets/hsbt.css")
end
