desc 'generate index.html'
task :generate do
  require 'kramdown'
  header = File.read('header.html')
  body = Kramdown::Document.new(File.read('index.md')).to_html
  footer = File.read('footer.html')
  File.open('index.html', 'w') do |f|
    [header, body, footer].each {|s| f.puts s}
  end

  require 'sassc'
  sass = File.read('hsbt.scss')
  File.open('hsbt.css', 'w') do |f|
    f.puts SassC::Engine.new(sass, style: :compressed).render
  end
end

desc 'deploy index.html'
task :deploy => [:generate] do
  require 'net/scp'
  Net::SCP.upload!('www.hsbt.org', 'hsbt', "index.html", "/var/www/hsbt.org/index.html")
  Net::SCP.upload!('www.hsbt.org', 'hsbt', "hsbt.css", "/var/www/hsbt.org/stylesheets/hsbt.css")
end
